.TH COUNT_FILES 1 "January 2026" "count-files 2.0" "User Commands"
.SH NAME
count_files \- count files, directories, symlinks and size in a directory
.SH SYNOPSIS
.B count_files
[\fBdirectory\fR] [\fBextension\fR]
.SH DESCRIPTION
The count_files script calculates:
.IP \[bu] 2
Number of regular files (optionally filtered by extension)
.IP \[bu] 2
Number of directories
.IP \[bu] 2
Number of symbolic links
.IP \[bu] 2
Total size of found files
.SH AUTHOR
nazarguitar
.SH LICENSE
MIT
